### ISSUE TITLE
plugin yandex-music

### ISSUE THREAD

**Issue by patridon87** [dobroweb/rhythmbox-plugin-yandex-music#20]
Добрый день! Не запускается плагин:
** (rhythmbox:17867): WARNING **: 10:50:25.419: Error importing plugin 'yandex-music':
Traceback (most recent call last):
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sergey/.local/share/rhythmbox/plugins/yandex-music/yandex-music.py", line 2, in <module>
    from yandex_music import Client
ModuleNotFoundError: No module named 'yandex_music'

(rhythmbox:17867): libpeas-WARNING **: 10:50:25.419: Error loading plugin 'yandex-music'

При этом апи музыки установлено и в питоне импортируется без проблем

**Comment by dobroweb** [comment]
Куда установлен api яндекс музыки? Какая ОС?
Можно узнать что было не так? Чтобы потом другим было понятно что делать в данной ситуации?

**Comment by patridon87** [comment]
ОС - popOS. Api установлен в системе (не venv). При запуске python в терминале импортируется без проблем. Проблему не решил.

**Comment by dobroweb** [comment]
Очень странно. Было подобное https://github.com/dobroweb/rhythmbox-plugin-yandex-music/issues/5 у другого пользователя на ОС Ubuntu 20.04 LTS. Но там дело дошло до переустановки ОС. Вы устанавливали от своего пользователя библиотеку или от пользователя root (sudo и далее)? Я попробую на чистой PopOS! установить плагин и также отпишусь.

**Comment by patridon87** [comment]
от своего. попробую через sudo

**Comment by patridon87** [comment]
sudo pip install yandex-music помогло! Спасибо!
