### ISSUE TITLE
AttributeError: module 'queue' has no attribute 'LifoQueue'

### ISSUE THREAD

**Issue by Execorn** [dobroweb/rhythmbox-plugin-yandex-music#46]
OS: Arch Linux x86_64
Kernel: 6.3.4-arch1-1

При попытке подключения плагина в rhythmbox выдается следующая ошибка:
`
Error importing plugin 'yandex-music':
Traceback (most recent call last):
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/rhythmbox/plugins/yandex-music/yandex-music.py", line 2, in <module>
    from yandex_music import Client
  File "/home/execorn/.local/lib/python3.11/site-packages/yandex_music/__init__.py", line 142, in <module>
    from .client import Client
  File "/home/execorn/.local/lib/python3.11/site-packages/yandex_music/client.py", line 48, in <module>
    from yandex_music.utils.request import Request
  File "/home/execorn/.local/lib/python3.11/site-packages/yandex_music/utils/request.py", line 12, in <module>
    import requests
  File "/home/execorn/.local/lib/python3.11/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/home/execorn/.local/lib/python3.11/site-packages/urllib3/__init__.py", line 17, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "/home/execorn/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 68, in <module>
    class ConnectionPool:
  File "/home/execorn/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 80, in ConnectionPool
    QueueCls = queue.LifoQueue
               ^^^^^^^^^^^^^^^
AttributeError: module 'queue' has no attribute 'LifoQueue'

(rhythmbox:135133): libpeas-WARNING **: 21:10:21.411: Error loading plugin 'yandex-music'
`

Судя по всему, где-то есть файл или папка queue которая мешает, но сам я найти ее не смог.
Похожая ошибка:
[https://github.com/eternnoir/pyTelegramBotAPI/issues/298](url)

**Comment by Execorn** [comment]
Проблема решилась. Начиная с версии rhythmbox 3.4.7 в фолдере /usr/lib/rhythmbox/plugins/listenbrainz есть файл и папка queue и при импорте ритмбокс все портит
решается удалением этой папки
