### ISSUE TITLE
Загрузка обложек

### ISSUE THREAD

**Issue by hjkbnm911** [dobroweb/rhythmbox-plugin-yandex-music#47]
Rhythmbox 3.4.7 модуль загрузки обложек не подгружает изображения при прослушивании треков с Яндекса.
rhythmbox[19801]: g_file_get_uri: assertion 'G_IS_FILE (file)' failed 
plasmashell[19801]: Traceback (most recent call last):
plasmashell[19801]:   File "/usr/lib/rhythmbox/plugins/artsearch/artsearch.py", line 96, in album_art_requested
plasmashell[19801]:     return s.next_search()    
plasmashell[19801]:            ^^^^^^^^^^^^^^^           
plasmashell[19801]:   File "/usr/lib/rhythmbox/plugins/artsearch/artsearch.py", line 57, in next_search
plasmashell[19801]:     search.search(self.key, self.last_time, self.store, self.search_done, None)
plasmashell[19801]:   File "/usr/lib/rhythmbox/plugins/artsearch/embedded.py", line 68, in search
plasmashell[19801]:     callback(args)
plasmashell[19801]:   File "/usr/lib/rhythmbox/plugins/artsearch/artsearch.py", line 61, in search_done
plasmashell[19801]:     self.next_search()
plasmashell[19801]:   File "/usr/lib/rhythmbox/plugins/artsearch/artsearch.py", line 57, in next_search
plasmashell[19801]:     search.search(self.key, self.last_time, self.store, self.search_done, None)
plasmashell[19801]:   File "/usr/lib/rhythmbox/plugins/artsearch/local.py", line 163, in search
plasmashell[19801]:     enumfiles = parent.enumerate_children_async("standard::content-type,access::can-read,standard::name", 0, 0, None, self._enum_children_cb, None)
plasmashell[19801]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
plasmashell[19801]: AttributeError: 'NoneType' object has no attribute 'enumerate_children_async'

**Comment by feschukov** [comment]
Добрый день. Не могу ничего сказать по плагину `artsearch`, это сторонний модуль и к текущему плагину никакого отношения не имеет. [Мой плагин](https://github.com/feschukov/rhythmbox-plugin-yandex-music) использует класс `AlbumArtManager` из файла [album_arts.py](https://github.com/feschukov/rhythmbox-plugin-yandex-music/blob/main/album_arts.py) для загрузки изображений альбомов. Что ожидает увидеть `artsearch` от класса трека мне не совсем понятно. Надо разбираться в связах.

**Comment by hjkbnm911** [comment]
То есть эта проблема только у меня, или же у всех кто использует плагин яндекса не отображаются обложки?
Отключил стандартный плагин поиска обложек,запустил в режиме отладки:

rhythmbox -D yandex-music
Yandex.Music plugin activating
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/yandex-music/entry.py", line 47, in feedback_track_started
    self.client.rotor_station_feedback_track_started(station=self.station, track_id=track)
  File "/home/oleg/.local/lib/python3.11/site-packages/yandex_music/client.py", line 70, in wrapper
    result = method(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oleg/.local/lib/python3.11/site-packages/yandex_music/client.py", line 1319, in rotor_station_feedback_track_started
    return self.rotor_station_feedback(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oleg/.local/lib/python3.11/site-packages/yandex_music/client.py", line 70, in wrapper
    result = method(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oleg/.local/lib/python3.11/site-packages/yandex_music/client.py", line 1274, in rotor_station_feedback
    result = self._request.post(url, params=params, json=data, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oleg/.local/lib/python3.11/site-packages/yandex_music/utils/request.py", line 286, in post
    result = self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oleg/.local/lib/python3.11/site-packages/yandex_music/utils/request.py", line 233, in _request_wrapper
    raise BadRequestError(message)
yandex_music.exceptions.BadRequestError: {'name': 'Radio session with id: <OLD>-xL2eCBzCYroM-2o5Z not found', 'message': ''} 

** (rhythmbox:51847): WARNING **: 12:10:03.070: Failed to send notification (Everyday): GDBus.Error:org.freedesktop.Notifications.Error.ExcessNotificationGeneration: Created too many similar notifications in quick succession
