### ISSUE TITLE
Не работает, пишет, что не удалось загрузить

### ISSUE THREAD

**Issue by grvinogradow** [dobroweb/rhythmbox-plugin-yandex-music#52]
Всё, что написала консоль в отладке ниже

rhythmbox:10161): Gtk-WARNING **: 15:37:26.642: actionhelper: action app.play-repeat can't be activated due to parameter type mismatch (parameter type b, target type NULL)

(rhythmbox:10161): Gtk-WARNING **: 15:37:26.643: actionhelper: action app.play-shuffle can't be activated due to parameter type mismatch (parameter type b, target type NULL)

(rhythmbox:10161): Rhythmbox-WARNING **: 15:37:26.740: Could not open device /dev/radio0
do_connect: could not connect to socket
connect: Нет такого файла или каталога

** (rhythmbox:10161): WARNING **: 15:37:34.924: Error importing plugin 'yandex-music':
Traceback (most recent call last):
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/misterairz/.local/share/rhythmbox/plugins/yandex-music/yandex-music.py", line 2, in <module>
    from yandex_music import Client
  File "/usr/local/lib/python3.10/dist-packages/yandex_music-2.1.1-py3.10.egg/yandex_music/__init__.py", line 142, in <module>
    from .client import Client
  File "/usr/local/lib/python3.10/dist-packages/yandex_music-2.1.1-py3.10.egg/yandex_music/client.py", line 48, in <module>
    from yandex_music.utils.request import Request
  File "/usr/local/lib/python3.10/dist-packages/yandex_music-2.1.1-py3.10.egg/yandex_music/utils/request.py", line 12, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/lib/python3/dist-packages/urllib3/__init__.py", line 13, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 43, in <module>
    from .util.queue import LifoQueue
  File "/usr/lib/python3/dist-packages/urllib3/util/queue.py", line 11, in <module>
    class LifoQueue(queue.Queue):
AttributeError: module 'queue' has no attribute 'Queue'

(rhythmbox:10161): libpeas-WARNING **: 15:37:34.924: Error loading plugin 'yandex-music'

**Comment by feschukov** [comment]
Добрый день. Была подобная проблема у другого пользователя https://github.com/feschukov/rhythmbox-plugin-yandex-music/issues/5#issuecomment-1095103367 на Ubuntu 20.04 LTS, но мы с ним так и не смогли разобраться в чём проблема. На чистом Ubuntu проверялось и всё работает корректно. У пользователя дело дошло до переустановки Ubuntu.

**Comment by grvinogradow** [comment]
> Добрый день. Была подобная проблема у другого пользователя [#5 (comment)](https://github.com/feschukov/rhythmbox-plugin-yandex-music/issues/5#issuecomment-1095103367) на Ubuntu 20.04 LTS, но мы с ним так и не смогли разобраться в чём проблема. На чистом Ubuntu проверялось и всё работает корректно. У пользователя дело дошло до переустановки Ubuntu.

И переустанавливал начисто и всё такое! Может проблема в конфигах? Может ритмбокс просто обновили и теперь не поддерживает? Я просто уже не знаю, что делать! Когда то нормально установилось, а теперь...

**Comment by grvinogradow** [comment]
в

> Добрый день. Была подобная проблема у другого пользователя [#5 (comment)](https://github.com/feschukov/rhythmbox-plugin-yandex-music/issues/5#issuecomment-1095103367) на Ubuntu 20.04 LTS, но мы с ним так и не смогли разобраться в чём проблема. На чистом Ubuntu проверялось и всё работает корректно. У пользователя дело дошло до переустановки Ubuntu.

я позже тогда посмотрю способ этого пользователя

**Comment by victorkitov** [comment]
Только что установленная Ubuntu 22.04. Плагин не работает. Пишет, что не удалось загрузить.

UPD. Решено переустановкой API яндекс.музыки `pip install yandex-music --upgrade`. Работает. 
Спасибо разработчикам за удобный плагин!
