### ISSUE TITLE
Кикнул все девайсы с акка и не могу использовать плагин

### ISSUE THREAD

**Issue by Supply12** [dobroweb/rhythmbox-plugin-yandex-music#57]
Я кикнул все девайсы с яндекс аккаунта,и теперь не могу использовать плагин.Категорий нет.
Вывод консоли:
`Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/yandex-music/yandex-music.py", line 29, in do_load
    if self.login_yandex():
       ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/rhythmbox/plugins/yandex-music/yandex-music.py", line 115, in login_yandex
    self.client = Client(token).init()
                  ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yandex_music/client.py", line 70, in wrapper
    result = method(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yandex_music/client.py", line 156, in init
    self.me = self.account_status()
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yandex_music/client.py", line 70, in wrapper
    result = method(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yandex_music/client.py", line 175, in account_status
    result = self._request.get(url, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yandex_music/utils/request.py", line 263, in get
    result = self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yandex_music/utils/request.py", line 231, in _request_wrapper
    raise UnauthorizedError(message)
yandex_music.exceptions.UnauthorizedError: {'name': 'session-expired', 'message': 'Your OAuth token is likely expired'} 
`
Как перезайти в акк?

**Comment by Supply12** [comment]
Господи,извиняюсь
Оказывается это решается сбросом токена через дконф

**Comment by Supply12** [comment]
Копия #9
